### ISSUE TITLE
Installs the unstripped binary BSpacr.so

### ISSUE THREAD

**Issue by yurivict** [sjaehn/BSpacr#2]
```
Warning: 'lib/lv2/BSpacr.lv2/BSpacr.so' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
```

The other binary (```BSpacr_GUI.so```) is installed stripped.

**Comment by falkTX** [comment]
because sometimes we just are oblivious to things..

@yurivict this is not a real plugin, please do not package it. it is a joke thing for april 1st. :toilet:

**Comment by yurivict** [comment]
I think we should celebrate April 1st every day of the year.
